version: 0.1
phases:
  install:
    commands:
      - echo installing nodejs...
      - npm install
      - echo nodejs installation done.
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      - echo building...
      - ng build --prod
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/hazardy