version: 0.1
phases:
  install:
    commands:
      - echo installing nodejs...
      - npm install
      - echo nodejs installation done.
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      - echo building...
      - ng build --prod
      - echo deploying...
      - aws s3 cp dist/hazardy/* s3://hazardy/
      - aws elasticbeanstalk update-environment --application-name "hazardy" --version-label "Sample Application-1" --environment-name "Hazardy-env"
      - echo deployment complete...